/*
 * generated by Xtext
 */
package cz.cvut.earlgrey.sequencemodel.ui.labeling;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class SequencemodelLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public SequencemodelLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	/**
	 * Returns Import's image used in Outline View.
	 * 
	 * @param ele Instance of an Import
	 * @return image's filename as String
	 */
	String image(EObject e) {
		if (e != null) {
			return e.eClass().getName() + ".gif";
		}
		return null;
	}

}
