/*
* generated by Xtext
*/
package cz.cvut.earlgrey.classmodel;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ClassmodelUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return cz.cvut.earlgrey.classmodel.ui.internal.ClassmodelActivator.getInstance().getInjector("cz.cvut.earlgrey.classmodel.Classmodel");
	}
	
}
