/*
 * generated by Xtext
 */
package cz.cvut.earlgrey.statemodel.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import com.google.inject.Inject;
import cz.cvut.earlgrey.statemodel.statemodel.Import;
import cz.cvut.earlgrey.statemodel.statemodel.State;
import cz.cvut.earlgrey.statemodel.statemodel.StateType;
import cz.cvut.earlgrey.statemodel.statemodel.Statemachine;
import cz.cvut.earlgrey.statemodel.statemodel.Statemodel;
import cz.cvut.earlgrey.statemodel.statemodel.Transition;

/**
 * Provides labels for a EObjects.
 * 
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class StatemodelLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public StatemodelLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	/**
	 * Returns Import's image used in Outline View.
	 * 
	 * @param ele Instance of an Import
	 * @return image's filename as String
	 */
	String image(Import ele) {
		return "Import.gif";
	}

	/**
	 * Returns Statemachine's image used in Outline View.
	 * 
	 * @param ele Instance of an Statemachine
	 * @return image's filename as String
	 */
	String image(Statemachine ele) {
		return "Statemachine.gif";
	}

	/**
	 * Returns State's image used in Outline View.
	 * 
	 * @param ele Instance of an State
	 * @return image's filename as String
	 */
	String image(State ele) {
		if (ele != null) {
			StateType type = ele.getType();
			if (type != null) {
				switch (type.getValue()) {
				case StateType.FINAL_VALUE:
					return "FinalState.gif";
				case StateType.INITIAL_VALUE:
					return "InitialNode.gif";
				default:
					return "State.gif";
				}
			}
		}
		return null;
	}

	/**
	 * Returns Transition's image used in Outline View.
	 * 
	 * @param ele Instance of an Transition
	 * @return image's filename as String
	 */
	String image(Transition ele) {
		return "Transition.gif";
	}

	/**
	 * Returns Statemodel's image used in Outline View.
	 * 
	 * @param ele Instance of an Statemodel
	 * @return image's filename as String
	 */
	String image(Statemodel ele) {
		return "Model.gif";
	}
}
