/*
 * generated by Xtext
 */
package cz.cvut.earlgrey.statemodel.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import cz.cvut.earlgrey.statemodel.statemodel.Statemachine;

/**
 * customization of the default outline structure
 * 
 */
public class StatemodelOutlineTreeProvider extends DefaultOutlineTreeProvider {

	public Object _text(Statemachine ele) {
		// System.out.println("ref " + ele.getRef().getNameRef());
		// System.out.println("name " + ele.getName());
		System.out.println(ele);
		return "statemachine";
	}
}
