/*
* generated by Xtext
*/
package cz.cvut.earlgrey.statemodel.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class StatemodelOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
