/*
* generated by Xtext
*/
package cz.cvut.earlgrey.sequencemodel.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SequencemodelOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
