/*
 * generated by Xtext
 */
package cz.cvut.earlgrey.annotation;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AnnotationRuntimeModule extends cz.cvut.earlgrey.annotation.AbstractAnnotationRuntimeModule {

}
