/*
* generated by Xtext
*/
package cz.cvut.earlgrey.statemodel.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StatemodelAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("cz/cvut/earlgrey/statemodel/parser/antlr/internal/InternalStatemodel.tokens");
	}
}
